### ISSUE TITLE
repository props should be an interface `IRepository`

### ISSUE THREAD

**Issue by moltar** [WtfJoke/cdk-github#23]
Instead of passing `repositoryName` and `repositoryOwner`, pass a single `repository` prop, which is an interface `IRepository`:

```ts
interface IGitHubRepository {
  owner: string
  name: string
}
```

https://github.com/WtfJoke/cdk-github/blob/88e509b07d1071bfbd2eeb239fd9c074d7079bcc/src/constructs/action-environment-secret.ts#L17-L26

Then your main GitHub construct would implement this interface.

**Comment by WtfJoke** [comment]
Hey Roman
Good idea, thanks for letting me know some improvments :)

Initially I had such a structure, but I especially in the beginning I struggled a lot with the limitations of custom resource and jsii (still do, but at least I know a bit more now 😄 ).
